### ISSUE TITLE
Document what the different graphs mean

### ISSUE THREAD

**Issue by jjasghar** [sexibytes/sexigraf#108]
I'm at a loss here.

A lot of the graphs are pretty self-explanatory, but take `distributed_fairness`, what does that mean?

Is there a glossary of what the default graphs look at? What is considered "good" or "bad?" I understand it's subjective, but a simple "higher number bad" "lower number bad" or that type of general idea would help greatly.

**Comment by rschitz** [comment]
Hi, if you don't know the "advanced" metrics already it's a bit tricky indeed. You need to dig into it.

You can start here: http://pubs.vmware.com/vsphere-65/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.PerformanceManager.html and here http://pubs.vmware.com/vsphere-65/index.jsp#com.vmware.wssdk.apiref.doc/vim.host.Summary.QuickStats.html

For example, here is what you can find about the fairness counters:

_Fairness scores are represented in units with relative values, meaning they are evaluated relative to the scores of other hosts. They should not be thought of as having any particular absolute value. Each fairness unit represents an increment of 0.001 in a fairness score. The further the fairness score diverges from 1, the less fair the allocation. Therefore, a fairness score of 990, representing 0.990, is more fair than a fairness score of 1015, which represents 1.015. This is because 1.015 is further from 1 than 0.990._

**Comment by jjasghar** [comment]
Oh amazing, thanks for the information 💯  🤘 

I guess I got some heavy reading todo :)
