### ISSUE TITLE
"No Data Points" Error

### ISSUE THREAD

**Issue by wright546** [sexibytes/sexigraf#210]
Hello Everyone,

I installed SexiGraf yesterday following the quick start guide.  I added 3 stand alone ESXi servers and I can see the VMs of each ESXi server in the offline inventory.  Today I'm trying to look at the metrics and what I'm seeing is confusing me.

1 - https://imgur.com/BV5XOTQ  https://imgur.com/1EAGLn6  The first screenshot is 6 hours, the second screenshot is 12 hours.  Why does the 6 hour view only show half of the data?

2 - https://imgur.com/fwOAcXd  How can I start troubleshooting why none of the ESXi servers or their metrics are showing up in this view?

3 - In the Credentials Store what does "VI" stand for?  I enabled VI for all 3 of the ESXi servers but I'm not sure if that's right since I don't know what it stands for.

4 - Do you need a paid ESXi license for SexiGraf to collect metrics?  Or does SexiGraf work with the free version of ESXi as well?

I've restarted the SexiGraf VM a couple of times but it hasn't helped.  I also updated the time zone in /etc/graphite/local_settings.py, as well as installed ntpdate and synced to an NTP server in my region.

Thanks

**Comment by rschitz** [comment]
Hi, thanks for your support

unmanaged ESX (not connected to a vcenter) is not supported by 0.99g but will be in 0.99f which is due soon. This will include ESX and VM metrics but also events.

you wont need a paid license for this to be supported since the license is only required for non-read-only operations.

check out https://github.com/sexibytes/sexigraf/issues/18
