### ISSUE TITLE
Export Dashboard data to CSV or Excel using Grafana or poweshell

### ISSUE THREAD

**Issue by mithun2186** [sexibytes/sexigraf#352]
Hello 

Is there a way to export data from dashboard directly or use  powershell script to export data to be used externally?

**Comment by rschitz** [comment]
Hi, for a one time export you can use the data inspector from grafana:
<img width="446" alt="image" src="https://github.com/sexibytes/sexigraf/assets/8385646/f8779652-eb12-435d-857a-488246a96dcf">

if you need automated recurent export, please describe your need because querying graphite would make more sense since it's where the data is actually stored
